/** Browser-plugin stylesheet: injected with the same lifecycle as the slot shadow. */
export const assistantCss = {
  root: 'dsh-codex-assistant-root',
  body: 'dsh-codex-assistant-body',
  stopped: 'dsh-codex-assistant-stopped',
  reasoning: 'dsh-codex-reasoning',
  reasoningRow: 'dsh-codex-reasoning-row',
  leading: 'dsh-codex-reasoning-leading',
  chevron: 'dsh-codex-reasoning-chevron',
  title: 'dsh-codex-reasoning-title',
  separator: 'dsh-codex-reasoning-separator',
  summary: 'dsh-codex-reasoning-summary',
  thinkBody: 'dsh-codex-reasoning-body',
  visuallyHidden: 'dsh-codex-visually-hidden',
} as const

export const assistantStyleText = [
  '.dsh-codex-assistant-root{display:flex;flex-direction:column;color:var(--dsw-alias-label-primary);font-size:16px;line-height:28px}',
  '.dsh-codex-assistant-body{display:flex;flex-direction:column;gap:16px}',
  '.dsh-codex-assistant-stopped{align-self:flex-start;padding:0 6px;border-radius:6px;background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:18px}',
  '.dsh-codex-reasoning{display:flex;flex-direction:column}',
  ".dsh-codex-reasoning[data-state='running'] .dsh-codex-reasoning-title{background-image:linear-gradient(90deg,var(--dsw-alias-label-secondary) 0%,var(--dsw-alias-label-secondary) 35%,var(--dsw-alias-label-primary) 50%,var(--dsw-alias-label-secondary) 65%,var(--dsw-alias-label-secondary) 100%);background-position:100% 0;background-size:250% 100%;background-clip:text;-webkit-background-clip:text;color:transparent;-webkit-text-fill-color:transparent;animation:dsh-codex-reasoning-text-shimmer 1.4s linear infinite}.dsh-codex-reasoning[data-state='running'] .dsh-codex-reasoning-summary{background-image:linear-gradient(90deg,var(--dsw-alias-label-tertiary) 0%,var(--dsw-alias-label-tertiary) 35%,var(--dsw-alias-label-primary) 50%,var(--dsw-alias-label-tertiary) 65%,var(--dsw-alias-label-tertiary) 100%);background-position:100% 0;background-size:250% 100%;background-clip:text;-webkit-background-clip:text;color:transparent;-webkit-text-fill-color:transparent;animation:dsh-codex-reasoning-text-shimmer 1.4s linear infinite}",
  '@keyframes dsh-codex-reasoning-text-shimmer{to{background-position:0 0}}',
  '.dsh-codex-reasoning-leading{flex-shrink:0}',
  '.dsh-codex-reasoning-chevron{color:var(--dsw-alias-label-secondary)}',
  '.dsh-codex-reasoning-title{font-weight:400}',
  '.dsh-codex-reasoning-separator{flex:none;width:2px;height:2px;margin:0 8px;border-radius:1px;background:var(--dsw-alias-label-caption)}',
  '.dsh-codex-reasoning-summary{min-width:0;overflow:hidden;flex:1 1 auto;color:var(--dsw-alias-label-tertiary);font-size:14px;line-height:24px;text-overflow:ellipsis;white-space:nowrap}',
  '.dsh-codex-reasoning-summary[data-follow-end]{text-overflow:clip}',
  '.dsh-codex-reasoning-body{padding:4px 0 4px 22px;color:var(--dsw-alias-label-tertiary);font-size:14px;line-height:24px;word-break:break-word}',
  '.dsh-codex-reasoning-body>div{color:inherit;font:inherit}',
  '.dsh-codex-reasoning-body.dsh-codex-reasoning-body :where(h1,h2,h3,h4,h5,h6){margin:8px 0;font:inherit!important;font-weight:600!important}',
  '.dsh-codex-reasoning-body.dsh-codex-reasoning-body :not(pre)>code{font-size:.875em!important;line-height:inherit!important}',
  '.dsh-codex-reasoning-body :where(p,ul,ol,blockquote,pre){margin-block:8px}',
  '.dsh-codex-visually-hidden{position:absolute;width:1px;height:1px;overflow:hidden;margin:-1px;padding:0;border:0;clip:rect(0 0 0 0);white-space:nowrap}',
  "@media (prefers-reduced-motion:reduce){.dsh-codex-reasoning[data-state='running'] .dsh-codex-reasoning-title{background:none;color:var(--dsw-alias-label-secondary);-webkit-text-fill-color:initial;animation:none}.dsh-codex-reasoning[data-state='running'] .dsh-codex-reasoning-summary{background:none;color:var(--dsw-alias-label-tertiary);-webkit-text-fill-color:initial;animation:none}}",
].join('\n')
